coverage:
  status:
    project:
      default:
        target: 60%
    patch:
      default:
        target: 60%

comment:
  layout: "reach,diff,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
