name: 🧪 Backend Tests & 📊 Codecov

on:
  push:
    branches: [tests]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build and test backend with coverage
        working-directory: backend
        run: mvn clean verify

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: backend/target/site/jacoco/jacoco.xml
          slug: lminervino18/researchers-page-conicet
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
